### ISSUE TITLE
Fix hidden navbar on mobile

### ISSUE THREAD

**Issue by ami** [robinjoseph08/pokedextracker.com#109]
![slack for ios upload](https://cloud.githubusercontent.com/assets/5498072/14518112/88f72926-01c9-11e6-9dc0-469be49e298f.jpg)

i thiniiinknknknk it might be a flexbox issue. we shall see.

**Comment by robinjoseph08** [comment]
This was happening for me too!! But it's weird cause it's not on prod. So I think it might be a local issue? We didn't change anything on the nav since the last deploy, right?

**Comment by ami** [comment]
i'm seeing it in prod too. i think it has to do with: https://github.com/robinjoseph08/pokedextracker.com/pull/96/files#diff-7ab7e672fb1c96b2cd0c3795ae50e1bdR47
