### ISSUE TITLE
Add indicator of caught status to sprites in evolution diagrams

### ISSUE THREAD

**Issue by Rooschach** [robinjoseph08/pokedextracker.com#144]
Another possibility for the issue raised in [#143](https://github.com/robinjoseph08/pokedextracker.com/issues/143). This would enable one to view the caught status of each mon in an evolutionary line by viewing the info for any mon in that line.

**Comment by ami** [comment]
thanks for the feedback, @Rooschach! i'm actually going to close this issue and combine it with #143.
