### ISSUE TITLE
Make repo work with node 6.5.0

### ISSUE THREAD

**Issue by rrbailey89** [robinjoseph08/pokedextracker.com#148]
Please create a wiki or elaborate on the installation guide for windows users following the readme when I type `npm i` my system tells me that it cannont find npm at all. However `nvm install 5` also installs `npm` so this error makes no sense to me.

**Comment by robinjoseph08** [comment]
Hey @rrbailey89!

Sorry you couldn't get it running. The installation instructions we have in the README should work for any OS/architecture that can run Node. It actually sounds like this doesn't have to do with this project specifically though. Seems more like an issue with your installation of `nvm`.

Are you using [`nvm-windows`](https://github.com/coreybutler/nvm-windows)? If you are, it seems like there are several open issues about `npm` not being installed along with `node`:

- https://github.com/coreybutler/nvm-windows/issues/124
- https://github.com/coreybutler/nvm-windows/issues/126
- https://github.com/coreybutler/nvm-windows/issues/199

If those don't prove to be helpful, I would recommend opening another issue and providing information specific to your situation (your version of Windows, if `npm` has ever worked for other version, etc).

If you can get `npm` functioning and `npm i` doesn't work specifically for this repo, then let us know! We'll happily take a look to see if it's something we can fix.

Thanks!

**Comment by rrbailey89** [comment]
@robinjoseph08 I currently have node 6.5.0 with its respective npm installed on my machine for another project. If I downgrade to 5 it breaks that project.  Is there a way to make your project compatible with 6.5.0? During install it seems to fail at post build.

**Comment by robinjoseph08** [comment]
@rrbailey89 cool, we can definitely look into this.

I tried with 6.5.0 as well and while I ran into errors after running `npm start`, my `npm i` seemed to "work". Can you tell me what the errors are regarding? I'm seeing issues with `node-sass` on my end. Is that what you're seeing too?

**Comment by rrbailey89** [comment]
@robinjoseph08 I dont think that I saw errors with node-sass. 

I cloned the most current repo and ran `npm i` which executed just fine it seemed however there were errors which I have attached at the following link [npm i errors](http://pastebin.com/9mzUXBbj) and this [link](http://pastebin.com/GBzCJYQ3) has the errors that I receive when I use `npm start` which im sure most relate to the failed install. After which I was able to access the webserver at localhost:8080 but it was just a solid white screen.

And thank you for taking a look into this :+1:

**Comment by robinjoseph08** [comment]
@rrbailey89 ahh gotcha. These errors are actually stemming from [`fsevents`](https://github.com/strongloop/fsevents) which is a Mac OSX only library. Normally, it's only required as an `optionalDependency` so other platforms don't encounter this issue, but we run `npm shrinkwrap` for this repo which locks in all of the installed dependencies (even optional ones). This is a [known issue](https://github.com/npm/npm/issues/2679) with `npm` and I'm trying a [workaround](https://github.com/npm/npm/issues/2679#issuecomment-150084700). Can you checkout the `make-fsevents-optional` branch and run `rm -rf node_modules && npm i`? I want to see if that will actually make `fsevents` optional.

**Comment by rrbailey89** [comment]
@robinjoseph08 that workaround seems to have gotten me farther. Now I receive this error:

```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) ins
tall the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of
the component to the system path if it is installed elsewhere.
```

which causes 2 or 3 different failures. `npm start` also still ends in a lot of failures and still results in a white page at `localhost:8080`

**Comment by robinjoseph08** [comment]
@rrbailey89 hmm are these errors coming from `node-sass`? I have a feeling this is just a Windows requirement for [Node addons](https://nodejs.org/api/addons.html). I know for Mac OS X, I need to have Xcode Command Line Tools installed before I can get anything working. Also, taking a look at the [`node-sass` repo](https://github.com/sass/node-sass#install), it makes a note about a Windows install require VS2013 (which includes a copy of the .NET Framework if I'm not mistaken).

Also you should get the latest commit from the `make-fsevents-optional` branch. That updates `node-sass` to the latest version because the version in master ([v3.4.2](https://github.com/sass/node-sass/releases/tag/v3.4.2)) doesn't support Node v6 while the latest version does.

**Comment by rrbailey89** [comment]
@robinjoseph08 it appears as though progress is being made. The command `npm i` no completes sucessfuly it appears. However `npm start` does not these are the errors.

```
ERROR in ./app/boot.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../config in F:\Ray\Downloads\PoGoMap\pokedextracker.com/app
 @ ./app/boot.ts 14:15-35

ERROR in ./app/services/api.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../../config in F:\Ray\Downloads\PoGoMap\pokedextracker.com/app\services
 @ ./app/services/api.ts 13:15-38

ERROR in ./app/styles/index.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/css-loader/index.js in F:\Ray\Downloads\PoGoMap\pokedextracker.com/app\styles
 @ ./app/styles/index.scss 4:14-122 13:2-17:4 14:20-128

ERROR in ./app/styles/index.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/style-loader/addStyles.js in F:\Ray\Downloads\PoGoMap\pokedextracker.com/app\styles
 @ ./app/styles/index.scss 7:13-71
```

**Comment by robinjoseph08** [comment]
Hmm... interesting. It might be an issue with file paths, but I can't say for certain. I'm going to try to install a Windows VM and see if I can determine any more details about this issue.

Can you provide me a few answers about your environment so I can try to emulate your problem?

1. What version of Windows are you using?
2. What version of `nvm-windows` are you using?
3. What shell are you using? (`cmd`, PowerShell, Git Bash, Cygwin, etc)
4. What version of `npm` are you using?
5. Do you do other active Node development on this machine?

**Comment by rrbailey89** [comment]
@robinjoseph08 

1. I am using Windows 10
2. I am not using nvm-winows, I use node 6.5.0
3. I use both cmd, and powershell
4. npm version is 3.10.3
5. I use other node apps that rely on node 6.5.0

I to also believe it is a file path issue somewhere.

**Comment by robinjoseph08** [comment]
Awesome, thanks! In regards to you not using `nvm-windows`, how did you install `nvm`? In your very first comment (the issue description), you mention running `nvm install 5`.

**Comment by rrbailey89** [comment]
@robinjoseph08 not a problem. I did install it to attempt following the directions. But soon discovered that it broke my PATH and also made the other node apps I use not work anymore. So I restored my system to just before the install which fixed everything.

**Comment by robinjoseph08** [comment]
@rrbailey89 okay, I think I figured it out! I was able to get it up and running in my VM. Turns out it was a path thing lol.

Can you get the last commit on the `make-fsevents-optional` branch again and check to see if it works for you too? If it does, I'll clean it up a bit and get that merged into master.

**Comment by rrbailey89** [comment]
@robinjoseph08 great! its working for me now too.

**Comment by howardycheung** [comment]
hi, i am struggling to make it work for me.
i have windows 10, trying to use 6.5.0
is the path solution working for you?
or I have to wait for a new build?
Thanks

**Comment by robinjoseph08** [comment]
Hey @howardycheung!

Yeah, I was able to get it running on my Windows 10 machine with v6.5.0 use the `make-fsevents-optional` branch. Are you seeing errors during the `npm i` stage or the `npm start` stage? Can you provide an error message/stack trace?

**Comment by howardycheung** [comment]
I used the latest trunk nvm (i think it is 1.1)
i did not get any error message during "nvm install 6.5.0"
at the end, i did a workaround to fix my issue.  a hack :)
I spent 2 - 3 hours of no avail so i have tried so many work arounds and with this solution at the end.
it finally works.
I hope to help someone to solve the issue without a build from branch.

I would however like to know the steps though to build from the branch you mentioned.
from the post, i think i was not patient to follow and dig up all the steps to do accordingly.

Here is my workaround steps: (i have tried so many different workarounds and found this one works)
1. installed nodejs via the normal windows way and note the installed folder.
2. afterward install nvm as usual via the setup
3. upon installation had been completed, i manually copied the npm folder to the nodejs folder inside the managed nvm folder.

and it works for me afterward to install gulp and bower via npm.

**Comment by robinjoseph08** [comment]
@howardycheung ah so you had issues with `nvm` and not with this repo specifically? That solution you mentioned seems to be the solution mentioned in [this PR](https://github.com/coreybutler/nvm-windows/issues/124#issuecomment-174047879). If it was an issue with `nvm`, then I might add a comment on the README saying to be wary of it for Windows.
