### ISSUE TITLE
Homepage base

### ISSUE THREAD

**Issue by ami** [robinjoseph08/pokedextracker.com#15]
### notes
- brief intro to app
- link to github
- register button

**Comment by ami** [comment]
@robinjoseph08 thinking about doing a homepage format like so (rough mockup below). basically, there's no "nav" - just two buttons to register and login. so every other page, other than home, has a nav.

![mockup](https://cloud.githubusercontent.com/assets/5498072/13978088/837ca7ea-f08b-11e5-92a9-938391c8342d.png)

angular-wise, should we keep our current structure and just hide the nav bar if you're on the home page? or should we rearrange the app/routes structure?

**Comment by robinjoseph08** [comment]
Hmm good question. I think it would be better if it was restructured, but it won't be too much. Essentially the nav won't be app.html, it'll be in each one that it'll actually be in (login, register, tracker). This requires some angular code changes though. I can do that part and as long as you only touch home.html, a rebase should be easy so you don't have to wait. Even though the home has a nav, just assume it won't be there and build according to that. Does that make sense?

**Comment by robinjoseph08** [comment]
btw make sure it's Poke **dex** Tracker lol

**Comment by ami** [comment]
okay that's what I thought, makes sense. and LOL I KEEP SOING THAT. It's right in the coded versionnnn
