### ISSUE TITLE
Error on safari preventing basic functionality

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#164]
when running pokedextracker.com on safari, there's an error that sometimes occurs that prevents all subsequent things from working (marking pokemon as captured, opening the info panel, showing error messages when logging in, etc). here's the error (though it's not super helpful in its current form):

<img width="727" alt="screenshot 2016-09-10 09 04 55" src="https://cloud.githubusercontent.com/assets/2454505/18411872/391fdda2-7736-11e6-9a0c-026fd7442269.png">

weird things:

- it only happens sometimes. i refreshed 3 times when logged in and on the tracker page and the first 2 times, it was fine but then it erred on the third
- i can't seem to reproduce it on chrome or firefox (though since it's non-deterministic, im not entirely sure its exclusive to safari)

ill probably have to dig into the bundle itself to see what the issue is. it might have to do with the minifying/uglifying we're doing only in prod. dont really know as of now

**Comment by ami** [comment]
@robinjoseph08 updated the description since we have now seen the issue in both prod and staging.
