### ISSUE TITLE
issues connecting

### ISSUE THREAD

**Issue by chagara** [robinjoseph08/pokedextracker.com#168]
Hello,

I git clone this project and I'm trying to test locally. But, I get connection issues when I run npm i I get a bunch of error connecting to 173.192.57.106:80 http://registry.nodejitsu.com/source-map/-/source-map-0.1.43.tgz

I checked firewalls ports and other things but, still it won't connect I turned firewall and everything off and still nothing.

I tried testing other websites connecting to port 80 and 443 and they work but, not this page. I also tried using a different network and get connection refused when I visit the page or try to re-run npm i

**Comment by chagara** [comment]
57575 info attempt registry request try #3 at 7:17:22 PM
57576 http fetch GET http://registry.nodejitsu.com/source-map/-/source-map-0.1.43.tgz
57577 error fetch failed http://registry.nodejitsu.com/source-map/-/source-map-0.1.43.tgz
57578 silly fetchPackageMetaData Error: connect ECONNREFUSED 173.192.57.106:80
57578 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:893:11)
57578 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:916:20)
57578 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
57578 silly fetchPackageMetaData  error for source-map@http://registry.nodejitsu.com/source-map/-/source-map-0.1.43.tgz { [Error: connect ECONNREFUSED 173.192.57.106:80]
57578 silly fetchPackageMetaData   code: 'ECONNREFUSED',
57578 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
57578 silly fetchPackageMetaData   syscall: 'connect',
57578 silly fetchPackageMetaData   address: '173.192.57.106',
57578 silly fetchPackageMetaData   port: 80 }
57579 silly rollbackFailedOptional Starting
57580 silly rollbackFailedOptional Finishing
57581 silly runTopLevelLifecycles Starting
57582 silly runTopLevelLifecycles Finishing
57583 silly install printInstalled
57584 verbose stack Error: connect ECONNREFUSED 173.192.57.106:80
57584 verbose stack     at Object.exports._errnoException (util.js:893:11)
57584 verbose stack     at exports._exceptionWithHostPort (util.js:916:20)
57584 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
57585 verbose cwd /home/jcasanova/Desktop/git_test/pokedextracker.com
57586 error Linux 4.4.0-36-generic
57587 error argv "/home/jcasanova/.nvm/versions/node/v5.12.0/bin/node" "/home/jcasanova/.nvm/versions/node/v5.12.0/bin/npm" "i"
57588 error node v5.12.0
57589 error npm  v3.8.6
57590 error code ECONNREFUSED
57591 error errno ECONNREFUSED
57592 error syscall connect
57593 error Error: connect ECONNREFUSED 173.192.57.106:80
57593 error     at Object.exports._errnoException (util.js:893:11)
57593 error     at exports._exceptionWithHostPort (util.js:916:20)
57593 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
57593 error  { [Error: connect ECONNREFUSED 173.192.57.106:80]
57593 error   code: 'ECONNREFUSED',
57593 error   errno: 'ECONNREFUSED',
57593 error   syscall: 'connect',
57593 error   address: '173.192.57.106',
57593 error   port: 80 }

**Comment by robinjoseph08** [comment]
Hey @chagara!

Sorry that you're having issues. This was actually a known issue and should've been fixed [14 days ago](https://github.com/robinjoseph08/pokedextracker.com/pull/145). Did you clone it recently or a while ago? If it was a while ago, can you try fetching from master, `rm -rf node_modules`, and try `npm i` again?

Let me know if this fixes it!

**Comment by chagara** [comment]
Helo,

I just cloned it earlier today.

**Comment by chagara** [comment]
let me redownload.

**Comment by chagara** [comment]
yep. works now. That was weird lol thanks for the help.

**Comment by robinjoseph08** [comment]
lol glad you got it working!
