### ISSUE TITLE
404 component design

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#43]
### why

if someone goes to a non-existent page, they should should see a 404, but the url should stay the same so it should be made into a component to be reused

**Comment by ami** [comment]
missingno? ;)

**Comment by robinjoseph08** [comment]
yassssss

**Comment by ami** [comment]
or luxio (national dex 404)??? http://bulbapedia.bulbagarden.net/wiki/Luxio_(Pok%C3%A9mon)

**Comment by robinjoseph08** [comment]
oooo thats also a good one! i think im still leaning toward missingno, but i do like the idea of luxio so you can pick
