### ISSUE TITLE
The info header varies in height for each pokemon

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#47]
![poke-info-bug](https://cloud.githubusercontent.com/assets/2454505/14026897/0d493276-f1c3-11e5-9afb-39a3dcb1df0b.gif)

**Comment by ami** [comment]
bahahhaha i appreciate the gif.

**Comment by ami** [comment]
did it take you a long time to figure out how to do that?

**Comment by robinjoseph08** [comment]
indeed it did. it was a two-step effort: 1) figuring out QT's UI to take the desired screencap (the first time, I didn't read how to stop recording so I had a minute long video of me struggling to stop it) and 2) finding a service to do the conversion since I don't have photoshop (ps. zamzar is pretty good).

so im glad you appreciate it

**Comment by ami** [comment]
although it wasn't really necessary cause i knew it was a problem already ^_________^

**Comment by robinjoseph08** [comment]
(⌣_⌣”)

**Comment by ami** [comment]
fixed by https://github.com/robinjoseph08/pokedextracker.com/issues/41

**Comment by robinjoseph08** [comment]
you should put an estimate so we can BURNDOWN :fire:
