### ISSUE TITLE
Make load times faster

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#49]
### notes

fetching 721 pokemon from the api is slow (~1.05**s**) because the response object is ginormous (~30**KB**) even with whitespace stripped out. Compare this to the user object that only takes 76**ms** of only ~70**B**.

### possible solutions

Honestly, I don't have many possible solutions :disappointed: the fact of the matter is that it's a lot of data that needs to be loaded. The only thing I can think of is to **not** make an API call to get that information. Since the Pokemon info doesn't change, we _could_ just keep the array of Pokemon on the client side. It's not the most elegant solution, but considering the fact that this info rarely changes, it's possible.

This still isn't the best best cause technically, this info is still being loaded when the bundled JS file gets loaded. ¯\\\_(ツ)_/¯ but loading it at that time might be better cause it only needs to load it once and then it's super fast for each page. And it's during the normal page load so it will "feel" faster. But, that means that even the home/login/register pages will load the Pokemon data even though it doesn't need it. BUT, most likely, if they hit one of those pages, they're gonna be viewing Pokemon very soon (after they login/register). 

So I'm conflicted. What do you think @ami?

**Comment by robinjoseph08** [comment]
ORRRRR we can just load :bear: necessities on page load (icon URL, name, and number) and then when each Pokemon is selected (since we're moving to a click-based selection), then we make another call to load the rest of the info? Huhhhhh? That could work too possibly.

**Comment by ami** [comment]
I think I'm leaning towards hitting the endpoint on click to load info. 

Don't you still have to hit the endpoint to load the dex side though? Or is that part easy / fast?

**Comment by robinjoseph08** [comment]
turns out im just dumb. it has very little to do with the size of the response cause theres another endpoint that is about the same size and is ~250ms.

i just wrote very inefficient code :disappointed: 

![bad](https://cloud.githubusercontent.com/assets/2454505/14038667/017d1d0e-f222-11e5-9308-d3c6cedbf138.jpg)

**Comment by ami** [comment]
l o l
