### ISSUE TITLE
Think about hosting our own images

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#52]
### notes

since we're just pulling assets from bulba's cdn (which is through http), it's making the "encrypted" thingy on chrome not green anymore:

<img width="89" alt="screen shot 2016-03-25 at 10 20 24 pm" src="https://cloud.githubusercontent.com/assets/2454505/14057769/20dbf8b2-f2d8-11e5-9fc2-5eced6362177.png">

vs.

<img width="78" alt="screen shot 2016-03-25 at 10 20 42 pm" src="https://cloud.githubusercontent.com/assets/2454505/14057778/38c9c238-f2d8-11e5-9a9a-40b1eef2cfd8.png">

i know there's no pressing need to host our assets, but it wouldn't be too terribly difficult to do either. just something to think about.

**Comment by ami** [comment]
reopening..
