### ISSUE TITLE
look into removing hover on mobile

### ISSUE THREAD

**Issue by ami** [robinjoseph08/pokedextracker.com#55]

**Comment by robinjoseph08** [comment]
was this taken care of already?

**Comment by ami** [comment]
i don't think so? this is about figuring how to remove hover styles on mobile so that when you click things, there's not the hover style in between/after

**Comment by robinjoseph08** [comment]
ah gotcha. i thought it was pertaining the hover styles for disabled on mobile that you fixed yesterday but now i realized this doesn't say disabled anywhere... sooo...

![image](https://cloud.githubusercontent.com/assets/2454505/14306013/652889ac-fb77-11e5-9a91-a591d1fa6408.png)

**Comment by robinjoseph08** [comment]
http://stackoverflow.com/a/8291715/2581607 looks like this can be solved with css media `screen` and `handheld` potentially

**Comment by robinjoseph08** [comment]
@ami hmmm okay so i think i can detect if mobile, but ideally, all of the `:hover` styles are all qualified with a parent class of `.no-touch` e.g. `.no-touch .other-class:hover {}`

wanna do that? :)

**Comment by ami** [comment]
@robinjoseph08 ya. wanna set it up working with one thing as an example? i think it'll be easier me to add everything after that. you can use `no-touch` for the class

**Comment by robinjoseph08** [comment]
yup, ill set it up :+1:
