### ISSUE TITLE
Replace home image + better responsiveness

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#57]
![image](https://cloud.githubusercontent.com/assets/2454505/14098971/2fab0fb2-f536-11e5-9633-43517fbda296.png)

**Comment by robinjoseph08** [comment]
also, this is how google sees our home page. not really sure why/how or if it even matters, just noting it.

<img width="534" alt="screen shot 2016-04-08 at 8 38 13 pm" src="https://cloud.githubusercontent.com/assets/2454505/14401493/e03f262e-fdc9-11e5-91cf-74056c2f4ffc.png">

**Comment by ami** [comment]
What is googlebot lol?

**Comment by robinjoseph08** [comment]
¯\\\_(ツ)_/¯ it's the google crawler that indexes our site i think, so this correlates to how google sees it. dunno what it actually means...

just tried to look up what it means, but actually, i think this might be fine. gahh honestly i dont know. i dont know what im doing lol.

BUT. one thing that we do have to keep in mind is the keywords that google affiliates with our site:

<img width="369" alt="screen shot 2016-04-08 at 8 54 13 pm" src="https://cloud.githubusercontent.com/assets/2454505/14401628/19d7275e-fdcc-11e5-9b98-5371d61077c2.png">

if you notice that its even pulling "san" and "francisco" more than some other more important things (like "living"). i _think_ maybe it's related to the types of tags we're using (`<p>` vs `<h1>` etc) so maybe we should have a sub heading or something that mentions living dex or something.

all this search stuff is getting me confused... (｢๑•₃•)｢ ʷʱʸ?
