### ISSUE TITLE
Add evolution details

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#58]
right now it's not super helpful beyond tracking since i still have to go to bulba to check evolution critia. if we add that info into the locations, all the better.

**Comment by robinjoseph08** [comment]
@ami so i've been thinking about this and ive come up with two ways to potentially do it:

- just update the `___location` fields in the db e.g. `Evolve from Bulbasaur` -> `Evolve from Bulbasaur (Level 16)`
  - pros:
    - it's relatively easy (no db migrations or api changes, just merely updating a field)
    - it fits in nicely with our current ui (no additional designs needed)
  - cons:
    - it's not very extensible i.e. we can't utilize this info in other places since it'll just be string data
    - while it fits nicely with our current ui, it doesn't help the user paint a picture of the whole evolution tree (like how bulba show evolutions) so if they're out catching a Weedle, they'll see that there are 3 in the evolution chain so they should catch 3 Weedles instead of rmrbing later and either coming back to the current location of just breeding (which takes longer)
- make new relationships in the form of an `evolutions` table
  - pros:
    - probably considered the "right way" to do this (these are relationships, so they should be represented as such
    - using this info, it'll be easier for us to aggregate that "todo list" e.g. you have a weedle but no kakuna? you can breed and evolve easily.
    - because it will allow us essentially bring that evolution graph from bulba into our site, it's one less reason for people to leave our site, making it more a "one-stop shop"
  - cons:
    - significantly more complicated (new migrations, serialization changes, consists of a self-referential many-to-many relationship which is always a bit messy, etc)
    - we'd have to come up with more ui components to accommodate this new info (similar to bulba's evolution graphs)

what do you think? im quite torn.

**Comment by ami** [comment]
does it make sense to do the first one for now (v1) and potentially look into adding the second later? because they're not mutually exclusive - there can still be those descriptions in the `locations` strings if and when we do decide to add the `evolutions` table and trees. UI wise, i don't think it would be that hard,  i would probably just add a section below the list of locations. sounds like the DB relationships and front-end part would be the hard part haha. thoughts?

**Comment by robinjoseph08** [comment]
Yeah I was also thinking about a v1/v2 iteration but the main qualm I have with that is that while that is relatively easy, there's still a lot of manual work involved with that method as well and, since it's just a string, I don't think I can "reuse" that work. So both involve that manual work and _ideally_, I don't wanna do that manual work twice.

So if you think the design work is easy, I think the front end part would also be easy. And if both methods require manual work, the primary difference seems to be setting up the relations and the required API changes. And so that makes me lean toward the relationship method.

**Comment by ami** [comment]
i see - makes sense. okieeeee let's do it :)

**Comment by ami** [comment]
completed!
