### ISSUE TITLE
Toggling captured fails on mobile safari

### ISSUE THREAD

**Issue by ami** [robinjoseph08/pokedextracker.com#67]
can you test it too, see if i'm not crazy?

i don't know if it fails on desktop safari, since my version still just crashes lols.

**Comment by robinjoseph08** [comment]
Hey @ami,

Sorry for the trouble you're having. It should be working on Safari as well. And it looks like we can't seem to replicate the issue on our end. Have you tried restarting your phone? That might solve it. While we try to sort this out, can you try using mobile Chrome instead? It's guaranteed to work on that browser.

Cheers,
Robin

**Comment by robinjoseph08** [comment]
both my desktop and mobile safari seem to be working... and i thought we got it to work on your version of safari? is that still broken?

i guess this is gonna require some IRL debugging

**Comment by ami** [comment]
toggling is fine, don't really know what happened that one time.
