### ISSUE TITLE
Find out why some HTML isn't rendering

### ISSUE THREAD

**Issue by robinjoseph08** [robinjoseph08/pokedextracker.com#80]
on mobile, the gender sign html on the pokemon component aren't rendering correctly:

![image](https://cloud.githubusercontent.com/assets/2454505/14401649/0ec834f6-fdcd-11e5-8085-4ea73f088b9c.png)

but it is for the info component:

![image](https://cloud.githubusercontent.com/assets/2454505/14401651/1a78ed5e-fdcd-11e5-82fd-ba27d7b40deb.png)

**Comment by ami** [comment]
i know why. it's not just on mobile, but on the responsive version on desktop too. i'll put up a fix.
